name: Update Weather Data
on:
  schedule:
    - cron: '0 8 * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install requests pandas
      
      - name: Run weather script
        run: python weather.py
      
      - uses: actions/upload-artifact@v4
        with:
          name: weather-data
          path: weather.csv