name: Weather Data Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  update-weather:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Debug - List files
        run: ls -la  # Mostra a estrutura de arquivos
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas
          pip list  # Mostra pacotes instalados
          
      - name: Run script with debug
        run: |
          echo "Checando se weather.py existe..."
          if [ -f "weather.py" ]; then
            echo "Executando script..."
            python -c "import sys; print(sys.path)"  # Debug Python path
            python weather.py
          else
            echo "❌ Arquivo weather.py não encontrado!"
            ls -la
            exit 1
          fi
          
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: debug-files
          path: |
            weather.csv
            *.log
